options:
  logging: CLOUD_LOGGING_ONLY  

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/core-plate-424123-h0/flask-app:latest', './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/core-plate-424123-h0/flask-app:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy/deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
 
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy/service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
images:
- 'gcr.io/core-plate-424123-h0/flask-app:latest'
